### ISSUE TITLE
There is no such thing as an empty string

### ISSUE THREAD

**Issue by rt121212121** [bico-media/b-cat#1]
ElectrumSV encodes an empty string as a 0 byte pushdata, or something to that effect. If you look at the transactions on the blockchain of Ryan X. Charles' photos, bcat seems to be given an single space not an empty string.

As long as your protocol refers to an empty string, it can not be implemented as there is no such thing.

**Comment by rt121212121** [comment]
To be clear, even with the disclaimer the whole empty string thing is ambiguous and confusing.

**Comment by mathiasrw** [comment]
Ok - makes sense. I changed it to NULL while having a footnote about strings with only certain chars will be regarded as NULL. 

Thank you for pointing this out...
