### ISSUE TITLE
raw transaction id is ambiguous

### ISSUE THREAD

**Issue by rt121212121** [bico-media/b-cat#2]
Please give an example in the specification to remove ambiguity. It could mean the byte ordering of the hash, or the byte ordering of the hex.

**Comment by mathiasrw** [comment]
I only saw this now. Sorry for late reply. 

Good input! 

I will update the example. If the hash is `ab4...2f3` the value must be `0xab4...2f3`

**Comment by mathiasrw** [comment]
Done!
