### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by alfredolopez80** [bico-media/b-cat#5]
Hey guys', do you have any examples???

**Comment by mathiasrw** [comment]
Have a look at 3bc9205b43bf8ca42856d798c2e959c18ffaaa5ff3212b11e9a07dd6cf303aa9

Data in a readable structure: https://bico.media/3bc9205b43bf8ca42856d798c2e959c18ffaaa5ff3212b11e9a07dd6cf303aa9/info

Final result: https://bico.media/3bc9205b43bf8ca42856d798c2e959c18ffaaa5ff3212b11e9a07dd6cf303aa9
